### ISSUE TITLE
Orion does not support Access to pages outside of Artemis

### ISSUE THREAD

**Issue by Wallenstein61** [ls1intum/Orion#30]
### Describe the bug
We have extended ArTEMiS at https://artemis.codeability.uibk.ac.at/ to be able to login with EduID, which is a Sibboleth-based Login-Mechanism.

When using ORION and logging in, we get the (German) error message: Orion unterstütz keine Zugriff auf Seiten außerhab von Artemis.

![image](https://user-images.githubusercontent.com/18215713/98568033-efeff100-22b0-11eb-89e8-99072e61e148.png)

#### To Reproduce

1. Go to https://artemis.codeability.uibk.ac.at/
2. Activate "Accept terms' Click on 'Sign in with your institution'
3. Select "Innsbruck" on the next page

#### Expected behavior
Login with EduId, then you will get automatically redirected back to ArTEMiS and authenticated.

#### Screenshots
see above

### Environment
not relevant.

#### Additional context
Instance of ArTEMiS für the Austrian CodeAbility Project

#### Output in IntelliJ
See Screenshot.

**Comment by nutatuna** [comment]
This is actually expected behavior. Artemis prevents access to any external webpages whose url does not start with the url you specified in the settings. Your site uses an intermediate page while redirecting, which is not the artemis site, it thus triggers the warning.

@ungaralex Any reason we need to prevent access to exeternal webpages? Do you think we can remove it, since to access other web pages the user has to consciously change the setting anyway.

**Comment by ungaralex** [comment]
This was the result of a discussion we had way back, where we decided to not let users break out of the "Artemis space" since we can't really guarantee what will happen as only the usage with the Artemis website is tested. 
Let's also say a teaching assistant links a code example and the student clicks on it. He is now outside of our domain and has no obvious way of going back, apart from re-opening the IDE/reloading in the settings/left-click context menu.

Now, for this specific case, we absolutely should allow users to use external login mechanisms. What I wanted to have and would be my favorite solution, is to remove the pop-up completely and then have a button above the browser (so an IDE-native button on top off the tool window next to the default ones), which always brings you back to the Artemis homepage if you have any problems whatsoever. An alternative would be to have a prominent button overlayed, having the same functionality, as soon as we detect a user leaving the domain. 
No matter what, removing the current blocking of external domains should be the first step @nutatuna .

**Comment by ungaralex** [comment]
@Wallenstein61 about the German message: Which language do you use in the IDE itself? If it's also German, this is intended as this is a pop-up inside the IDE. If it's English, we also have to check the translations in the plugin

**Comment by nutatuna** [comment]
@ungaralex Done it. I will add your suggestion in the future. It should be able to go to the login page now. I don't have an edu account so I can't test further.

**Comment by Wallenstein61** [comment]
@ungaralex about the German message: German was fine in my case . Was not sure whether other participants in this forum can understand German :-)
