### ISSUE TITLE
Change Repository Path

### ISSUE THREAD

**Issue by JunkyDeveloper** [ls1intum/Orion#6]
The plugin looks good, and i tested that only with one Project. But you create a folder in /%User%/ Dictionary. But i want so save repositores on an other disk in a specific folder.
I need an option to change your create/clone path to my on path. Then I will use your plugin more often.

**Comment by ungaralex** [comment]
Thank you very much for the feedback. 
There already is an option to change the home folder for exercises. Go to Settings > Tools > Orion. There you should find the option to change the path. If you are using Windows, I would suggest you download and install the latest release since it contains some important fixes for your OS.

**Comment by JunkyDeveloper** [comment]
Ok Thanks, I didn't see that option and that will help a lot of people. But I have two Paths to clone my Repos. One for my Homework and one for Tutorien. This is why I need a option to change Path or to configure more than one Path.

Currently I use your Plugin only to get the informations from Artemis. Thats only an idea if you have some free time 😆
